# Generated by Django 4.0.4 on 2022-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('excelFile', models.FileField(upload_to='')),
            ],
        ),
    ]
